import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import test from "node:test";

const automationNotice =
  "AUTOMATION-CONTROL: This prompt was generated by a whetstone launcher, not written by Francis. " +
  "Do not correct it or append any English-learning corpus record for it, including a record with " +
  "includeInDrills=false.";

test(
  "Windows one-shot launchers propagate selector failures",
  { skip: process.platform !== "win32" },
  () => {
    const testDir = mkdtempSync(join(tmpdir(), "whetstone-launcher-test-"));
    try {
      const failingSelector = join(testDir, "fail-selector.cmd");
      writeFileSync(failingSelector, "@echo off\r\necho selector failed 1>&2\r\nexit /b 7\r\n");
      for (const launcher of ["run-developer.cmd"]) {
        const result = spawnSync(
          process.env.ComSpec ?? "cmd.exe",
          ["/d", "/c", resolve("scripts", launcher)],
          {
            cwd: resolve("."),
            encoding: "utf8",
            env: {
              ...process.env,
              WHETSTONE_SELECTOR_COMMAND: failingSelector
            }
          }
        );
        assert.equal(result.status, 7, `${launcher}\n${result.stdout}\n${result.stderr}`);
        assert.match(result.stderr, /selector failed/);
      }
    } finally {
      rmSync(testDir, { recursive: true, force: true });
    }
  }
);

test(
  "generated worker prompts identify automation before the task",
  { skip: process.platform !== "win32" },
  () => {
    const testDir = mkdtempSync(join(tmpdir(), "whetstone-prompt-test-"));
    try {
      const invocationFile = join(testDir, "invocation.txt");
      writeFileSync(
        join(testDir, "copilot.cmd"),
        [
          "@echo off",
          `> "${invocationFile}" echo %*`,
          `>> "${invocationFile}" echo context=%WHETSTONE_AUTOMATION_CONTEXT%`,
          "exit /b 17",
          ""
        ].join("\r\n")
      );
      writeFileSync(join(testDir, "node.cmd"), "@echo off\r\necho test 1\r\n");

      for (const { launcher, args } of [
        { launcher: "run-developer.cmd", args: ["733"] },
        { launcher: "run-tester.cmd", args: [] },
        { launcher: "run-tester-auto.cmd", args: [] }
      ]) {
        const result = spawnSync(
          process.env.ComSpec ?? "cmd.exe",
          ["/d", "/c", resolve("scripts", launcher), ...args],
          {
            cwd: resolve("."),
            encoding: "utf8",
            env: {
              ...process.env,
              PATH: `${testDir};${process.env.PATH ?? ""}`
            }
          }
        );

        const invocation = readFileSync(invocationFile, "utf8");
        assert.notEqual(result.status, 0, `${launcher} did not invoke the failing Copilot stub`);
        assert.ok(invocation.includes(automationNotice), `${launcher}\n${invocation}`);
        assert.match(invocation, /\r?\ncontext=1\r?\n?$/);
        if (launcher === "run-developer.cmd") {
          assert.match(invocation, /--model claude-sonnet-5(?:\s|$)/);
          assert.match(invocation, /--effort high(?:\s|$)/);
        }
      }
    } finally {
      rmSync(testDir, { recursive: true, force: true });
    }
  }
);

test(
  "developer wait path runs deterministic merge and dependency unblock without a model",
  { skip: process.platform !== "win32" },
  () => {
    const testDir = mkdtempSync(join(tmpdir(), "whetstone-finalize-test-"));
    try {
      const callsFile = join(testDir, "node-calls.txt");
      const copilotFile = join(testDir, "copilot-called.txt");
      const selector = join(testDir, "wait-selector.cmd");
      writeFileSync(selector, "@echo off\r\necho wait 42\r\n");
      writeFileSync(
        join(testDir, "node.cmd"),
        `@echo off\r\n>> "${callsFile}" echo %*\r\nexit /b 0\r\n`
      );
      writeFileSync(
        join(testDir, "copilot.cmd"),
        `@echo off\r\n> "${copilotFile}" echo called\r\nexit /b 0\r\n`
      );

      const result = spawnSync(
        process.env.ComSpec ?? "cmd.exe",
        ["/d", "/c", resolve("scripts", "run-developer.cmd")],
        {
          cwd: resolve("."),
          encoding: "utf8",
          env: {
            ...process.env,
            PATH: `${testDir};${process.env.PATH ?? ""}`,
            WHETSTONE_SELECTOR_COMMAND: selector
          }
        }
      );

      assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
      const calls = readFileSync(callsFile, "utf8");
      assert.match(calls, /scripts\\delivery\\mergeReadyPrs\.mjs/);
      assert.match(calls, /scripts\\delivery\\unblockReadyIssues\.mjs/);
      assert.throws(() => readFileSync(copilotFile, "utf8"), /ENOENT/);
    } finally {
      rmSync(testDir, { recursive: true, force: true });
    }
  }
);
