import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { afterEach, describe, expect, it } from "vitest";

import { parseRangeConversion, PINNED_MODEL_COMMIT, PINNED_MODEL_REPO } from "@whetstone/contracts";

import {
  canEnforceStructuredPdfMemoryCeiling,
  createDoclingRunner,
  issueStagedFileHandle
} from "../../files/pdfStructuredAdapter.js";
import { createImageResourceStore } from "../../files/imageResourceStore.js";
import { hashBytes } from "../../files/sourceFileStore.js";
import { defaultStructuredPdfMemoryMib } from "../../config/serverConfig.js";
import { adoptRangeArtifacts, collectAdoptedArtifacts } from "./pdfImportArtifacts.js";

// #807 real-toolchain contract: prove that a PDF picture the pinned Docling can render survives the whole
// figure-preservation chain — worker render -> server-side artifact adoption -> content-addressed image
// store — as the SAME servable resource the Reader returns. The synthetic public fixture (figure.pdf,
// generated by scripts/probes/make_figure_pdf.py) carries a heading, a paragraph, and one embedded raster
// image so the layout model classifies a real PictureItem. This is the only test exercising the real
// render-to-Reader path end to end, so it guards that chain against regressing to a placeholder-only import.
//
// The deterministic fail-before/pass-after coverage of adoption, mapping, and publication lives in the fast
// unit lanes (pdfImportArtifacts / pdfCanonicalMapping / pdfImportPublish tests). This real-lane test does
// not re-prove those units; it proves the pinned toolchain actually produces a picture artifact whose bytes
// the image store serves under the id the canonical figure references.
//
// It is skip-guarded on the full real lane (a supported memory-boundary platform plus an importable Docling
// with the pinned model snapshot cached). CI does not provision that heavy toolchain, so it skips cleanly;
// `it`/`it.skip` is chosen at collection time from a synchronous probe.
function detectRealLane(): { python: string } | null {
  if (!canEnforceStructuredPdfMemoryCeiling(process.platform)) {
    return null;
  }
  const probe =
    `import docling;from huggingface_hub import snapshot_download;` +
    `snapshot_download('${PINNED_MODEL_REPO}',revision='${PINNED_MODEL_COMMIT}',local_files_only=True)`;
  for (const python of ["python", "python3"]) {
    try {
      execFileSync(python, ["-c", probe], { stdio: "ignore" });
      return { python };
    } catch {
      // interpreter missing, or Docling/models not provisioned — try the next candidate, else skip.
    }
  }
  return null;
}

const realLane = detectRealLane();
const workerScriptPath = fileURLToPath(new URL("../../files/pdf_to_docling.py", import.meta.url));
const figurePdfPath = fileURLToPath(
  new URL("../../files/tests/fixtures/structured/figure.pdf", import.meta.url)
);

const cleanupDirs: string[] = [];

afterEach(async () => {
  await Promise.all(cleanupDirs.splice(0).map((dir) => rm(dir, { force: true, recursive: true })));
});

async function makeTempDir(prefix: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), prefix));
  cleanupDirs.push(dir);
  return dir;
}

describe("PDF figure Reader contract (real Docling)", () => {
  const realLaneIt = realLane ? it : it.skip;
  realLaneIt(
    "renders an extractable PDF picture into a PNG the image store serves to the Reader (#807)",
    async () => {
      const stageRoot = await makeTempDir("whetstone-figure-stage-");
      await writeFile(join(stageRoot, "figure.pdf"), new Uint8Array(readFileSync(figurePdfPath)));
      const handle = issueStagedFileHandle(stageRoot, "figure.pdf");

      const runner = createDoclingRunner({
        pythonBinary: realLane!.python,
        scriptPath: workerScriptPath,
        perRangeTimeoutMs: 120_000,
        memoryMib: defaultStructuredPdfMemoryMib(process.platform)
      });

      const probe = await runner.probe(handle.path, undefined);
      expect(probe.status).toBe("ok");
      if (probe.status !== "ok") throw new Error("expected an ok probe outcome");

      // Give the range its own server-owned artifact directory, exactly as the production runner does inside
      // the retained attempt stage, and let the worker render each renderable picture into it.
      const artifactDir = join(stageRoot, "artifacts", "0");
      await mkdir(artifactDir, { recursive: true });
      const outcome = await runner.convertRange(
        handle.path,
        1,
        probe.pageCount,
        undefined,
        artifactDir
      );
      expect(outcome.status).toBe("ok");
      if (outcome.status !== "ok") throw new Error("expected an ok range outcome");

      const parsed = parseRangeConversion(outcome.raw);
      expect(parsed.status).toBe("ok");
      if (parsed.status !== "ok") throw new Error(`range payload invalid: ${parsed.status}`);

      // Adopt through the SAME server gate publication trusts: read each ref's PNG and verify
      // type/digest/length/dimensions before it is allowed onto a canonical figure.
      const adopted = await adoptRangeArtifacts({
        payload: parsed.value,
        rangeIndex: 0,
        adoptedBytesSoFar: 0,
        readArtifact: (fileName) => readFile(join(artifactDir, fileName))
      });
      expect(adopted.status).toBe("ok");
      if (adopted.status !== "ok") throw new Error(`adoption failed: ${adopted.detail}`);

      const artifacts = collectAdoptedArtifacts(adopted.payload);
      expect(artifacts.length).toBeGreaterThanOrEqual(1);
      const figure = artifacts[0]!;

      // Store the validated PNG bytes through the existing content-addressed boundary, as publication does.
      const bytes = new Uint8Array(await readFile(join(artifactDir, "fig-0.png")));
      const imageResourceStore = createImageResourceStore(
        await makeTempDir("whetstone-figure-img-")
      );
      const { id } = await imageResourceStore.store({ bytes, contentType: "image/png" });

      // Content addressing makes the stored id the figure's imageResourceId: sha256 of the bytes, which is
      // exactly the manifest digest adoption verified. The canonical figure would reference this id.
      expect(id).toBe(figure.sha256);
      expect(hashBytes(bytes)).toBe(id);

      // The Reader serves precisely what `imageResourceStore.read(id)` returns (see imageRoutes.ts): the PNG
      // bytes under an allowed image content type. Proving that read resolves is proving the artifact reaches
      // the Reader.
      const served = await imageResourceStore.read(id);
      expect(served).toBeDefined();
      expect(served!.contentType).toBe("image/png");
      expect(served!.bytes.byteLength).toBe(figure.byteLength);
      expect(hashBytes(served!.bytes)).toBe(figure.sha256);
    },
    130_000
  );
});
